### PR TITLE
BUG-968: When deleting an user the console shows a lot of errors

### LINKED ISSUE #968: When deleting a user the console shows a lot of errors
**Preconditions**
None.

**Steps To Reproduce**
1. Log in to the system
2. Go to My account page
3. Click the delete user link
5. Open the dev console
4. Delete the user

**Expected behavior**
The console shouldn't show errors in the process.

**Actual behavior**
The console shows error when deleting the user.

**Screenshots**
delete user error

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version Dev- 194

**Additional context**
None.

### PR DESCRIPTION
**Pull request by jricaldi**
Relates to #968

### CODE REVIEW

File: src/services/source.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export namespace source {
     export async function deleteDataFromUserAccount(userId: string) {
         const query: Query = new Query();
         query.add({ parameter: "userId", value: userId });
-        const finalURL = SOURCE_URL + "deleteUserAccount/";
+        const finalURL = SOURCE_URL + "v1/deleteUserAccount/";
```
Comment (jricaldi) [inline src/services/source.ts]: @AnkRaiza apparently this was missing when changing the value of the constants in the top of the file.

Comment (jricaldi) [reply src/services/source.ts]: it was fix by PR: https://github.com/bespoken/dashboard/pull/982
