### PR TITLE
Fixes for source list order, ssml text format, login reset password button new alignment

### LINKED ISSUE #343: Place "Reset Password" link underneath the sign-in box
It should go below the white area, to make the buttons seem less crowded.

Additionally, I would remove two of the lines:
1) The one above Register and Login
2) The one above Login with Github

Lastly, I would give all the buttons a background color, even when not selected. A blue similar to the color of the reset password link could work.

screen shot 2017-05-29 at 3 11 27 pm

### PR DESCRIPTION
**Pull request by AnkRaiza**
Fixes #343 , #342 , #335 

Changes in this pull request include:
-conversation.ts
-conversational buble
-source list order
-login page

### CODE REVIEW

File: src/pages/SourceListPage.tsx [hunk 1]
```diff
@@ -34,10 +34,15 @@ function mapStateToProps(state: State.All) {
 export class SourceListPage extends React.Component<SourceListPageProps, SourceListPageState> {
 
     render() {
+        const sortedList = this.props.sources.sort((a, b) => {
```
Comment (jperata) [inline src/pages/SourceListPage.tsx]: since string already manage comparison operators , you can just do, sources.sort() , it will sort in asc order, if you need desc you can use revert

File: src/models/conversation.ts [hunk 2]
```diff
@@ -282,8 +282,10 @@ class AlexaConversation extends GenericConversation {
 
     get ssmlText(): string | undefined {
       const ssmlString = propertyExist(this.response, "payload", "response", "outputSpeech", "ssml") ? this.response.payload.response.outputSpeech.ssml : undefined;
-      const removedSpeak = ssmlString ? ssmlString.replace("<speak>", "").replace("</speak>", "").trim() : undefined;
-      return removedSpeak ? removedSpeak.replace(/src=".*?"|src='.*?'/g, '"..."') : undefined;
+      const audioUrls = ssmlString ? ssmlString.match(/src=".*?"|src='.*?'/) : undefined;
```
Comment (jperata) [inline src/models/conversation.ts]: why not
const audioUrls = ssmlString && ssmlString.match(/src=".*?"|src='.*?'/) ; 
same for the rest

Comment (jperata) [inline src/models/conversation.ts]: If you need the explicit undefined for some reason you can just return it at the end

File: src/pages/SourceListPage.tsx (hunk 1 above)
Comment (AnkRaiza) [inline src/pages/SourceListPage.tsx]: this is an array of objects so i have to map to the correct property to sort also, using just sort() wont fix the case insensitive issue
