### PR TITLE
Exception filter

### LINKED ISSUE #125: Ability to Filter By Exceptions on Logs Page
In order to just view the exceptions within a set of logs, we should be able to toggle a filter to just view logs with crashes.

### PR DESCRIPTION
**Pull request by chrsdietz**
Fixes #125

Changes in this pull request include:
- Added a filter to gather all conversations with exceptions.

### CODE REVIEW

File: src/pages/logspage/FilterBar/FilterBar.tsx [hunk 1]
```diff
@@ -139,7 +152,16 @@ class FilterBar extends React.Component<FilterProps, FilterState> {
                         value={this.state.intentValue}
                         onChange={this.handleIntentChange} />
                 </Cell>
-                <Cell col={2} offsetDesktop={4} tablet={2} offsetTablet={8} phone={2} offsetPhone={0}>
+                <Cell col={1} offsetDesktop={0} tablet={1} offsetTablet={0} phone={4} offsetPhone={0}>
+                    <div style={{ position: "relative", top: "50%", transform: "translate(0%, -50%)" }} >
+                        <Checkbox
+                            theme={CheckboxTheme}
+                            checked={this.state.exceptionsOnly}
+                            label="Only with Exceptions"
```
Comment (michaelmyers) [inline src/pages/logspage/FilterBar/FilterBar.tsx]: "With Exceptions" might be more appropriate since the logs can also have other things, like error messages.
