### PR TITLE
Fix 196

### LINKED ISSUE #196: Selected Log Disappears When you Request More Logs
### Expected Behavior

When I select a log to view, then scroll down the list of logs, I expect the selected log details to remain.

### Actual Behavior

The detail disappears when more logs are requested by scrolling.  

selected-log-disappears

### Reproduction Steps

1.  Open the log explorer
2.  Select a log
3.  Scroll down

### PR DESCRIPTION
**Pull request by chrsdietz**
Fixes #196 

Changes in this pull request include:
- Now only clearing out the log when the source is different.

### CODE REVIEW

File: src/pages/logspage/LogsExplorer/LogsExplorer.tsx [hunk 1]
```diff
@@ -44,8 +44,12 @@ export default class LogExplorer extends React.Component<LogExplorerProps, LogEx
     }
 
     componentWillReceiveProps?(nextProps: LogExplorerProps, nextContext: any): void {
-        this.state.selectedConvo = undefined;
-        this.setState(this.state);
+        console.log(this.props.source);
+        console.log(nextProps.source);
```
Comment (michaelmyers) [inline src/pages/logspage/LogsExplorer/LogsExplorer.tsx]: console.log

Comment (chrsdietz) [inline src/pages/logspage/LogsExplorer/LogsExplorer.tsx]: Already done

Comment (michaelmyers) [inline src/pages/logspage/LogsExplorer/LogsExplorer.tsx]: We had a review race condition.
